%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 465
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 524.2422531097977
   fy: 524.2422531097977
   cx: 320.5
   cy: 225.5
