%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 465
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 525.7
   fy: 525.7
   cx: 320.0
   cy: 240.0
